// <auto-generated />
using System;
using HttpAPIs.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppContext = HttpAPIs.Database.AppContext;

namespace HttpAPIs.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HttpAPIs.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3ceee8d-f995-4d75-8c23-7fd293f460c5"),
                            Age = 25,
                            FirstName = "Humza",
                            Gender = "Male",
                            LastName = "Tufail"
                        },
                        new
                        {
                            Id = new Guid("c3110344-691a-493a-ab11-bb19b6b43be8"),
                            Age = 25,
                            FirstName = "Salman",
                            Gender = "Male",
                            LastName = "AK"
                        },
                        new
                        {
                            Id = new Guid("3af2a713-881c-4613-bb51-032fbea1bb25"),
                            Age = 25,
                            FirstName = "Hadid",
                            Gender = "Male",
                            LastName = "Bushra"
                        },
                        new
                        {
                            Id = new Guid("0abd785e-73cb-4652-8ab4-507637fcf12c"),
                            Age = 25,
                            FirstName = "Zeeshan",
                            Gender = "Male",
                            LastName = "Maaao"
                        },
                        new
                        {
                            Id = new Guid("7da3c572-fc78-4ce0-a0d3-6a169861119b"),
                            Age = 25,
                            FirstName = "Amaid",
                            Gender = "Male",
                            LastName = "Haider"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
